import {
  Indicator,
  Target,
  MonthlyProgress,
  Evidence,
  ActionDirective,
  User,
  Department,
  StrategicIssue,
  SystemConfig,
  ActivityLog,
  MonthlyReport,
  Personnel,
} from './types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    departmentId: 'DEP-001',
    id: 'DEP-001',
    departmentName: 'งานวิชาการ',
    name: 'งานวิชาการ',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบงานวิชาการ การจัดการเรียนการสอน หลักสูตร และการพัฒนาอาจารย์',
    responsiblePersonIds: ['PER-0005', 'PER-0006'],
    responsiblePersonNames: ['นายเลิศยศ เผื่ออำนาจ', 'นายชลธิวัฒน์ นุ้ยไกร'],
    displayOrder: 1,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-002',
    id: 'DEP-002',
    departmentName: 'งานพัฒนานักศึกษา',
    name: 'งานพัฒนานักศึกษา',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบกิจกรรมนักศึกษา ทุนการศึกษา วินัยและสวัสดิการนิสิต ศิษย์เก่าสัมพันธ์',
    responsiblePersonIds: ['PER-0007'],
    responsiblePersonNames: ['น.ส.บุษรอ นิโลง'],
    displayOrder: 2,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-003',
    id: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    name: 'งานวิจัยและพัฒนาท้องถิ่น',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบการส่งเสริมงานวิจัย บริการวิชาการ นวัตกรรมสังคม และการพัฒนาเชิงพื้นที่',
    responsiblePersonIds: ['PER-0008'],
    responsiblePersonNames: ['น.ส.ศศิธร อินน้ำหอม'],
    displayOrder: 3,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-004',
    id: 'DEP-004',
    departmentName: 'งานศิลปะและวัฒนธรรม',
    name: 'งานศิลปะและวัฒนธรรม',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบการทำนุบำรุงศิลปะและวัฒนธรรม อนุรักษ์ภูมิปัญญาท้องถิ่น และ Soft Power',
    responsiblePersonIds: ['PER-0009'],
    responsiblePersonNames: ['น.ส.จิรชยา ฉวีอินทร์'],
    displayOrder: 4,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-005',
    id: 'DEP-005',
    departmentName: 'งานประกันคุณภาพการศึกษา',
    name: 'งานประกันคุณภาพการศึกษา',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบการประกันคุณภาพการศึกษา AUN-QA, EdPEx, สมศ. และมาตรฐานวิชาการ',
    responsiblePersonIds: ['PER-0010'],
    responsiblePersonNames: ['น.ส.ปิยะมาศ สร้อยแก้ว'],
    displayOrder: 5,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-006',
    id: 'DEP-006',
    departmentName: 'งานบริหาร บุคคล และการเงิน',
    name: 'งานบริหาร บุคคล และการเงิน',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบการบริหารทั่วไป ทรัพยากรบุคคล การเงินและบัญชี พัสดุและอาคารสถานที่',
    responsiblePersonIds: ['PER-0011'],
    responsiblePersonNames: ['นายชนินทร์ มาทวี'],
    displayOrder: 6,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-007',
    id: 'DEP-007',
    departmentName: 'งานสำนักงานคณบดี',
    name: 'งานสำนักงานคณบดี',
    departmentType: 'งานสำนักงานคณะ',
    type: 'งานสำนักงานคณะ',
    description: 'รับผิดชอบงานประสานงานผู้บริหาร งานสารบรรณ งานประชุมคณะกรรมการประจำคณะ งานวิเทศสัมพันธ์',
    responsiblePersonIds: ['PER-0005', 'PER-0011'],
    responsiblePersonNames: ['นายเลิศยศ เผื่ออำนาจ', 'นายชนินทร์ มาทวี'],
    displayOrder: 7,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
  {
    departmentId: 'DEP-008',
    id: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    name: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    departmentType: 'กลุ่มผู้บริหาร',
    type: 'กลุ่มผู้บริหาร',
    description: 'กำกับนโยบายยุทธศาสตร์ การขับเคลื่อนพันธกิจคณะ และการตัดสินใจเชิงบริหาร',
    responsiblePersonIds: ['PER-0001', 'PER-0002', 'PER-0003', 'PER-0004'],
    responsiblePersonNames: [
      'ผศ.สวพร จันทรสกุล (คณบดี)',
      'อ.ชลธิชา สุรัตนสัญญา (รองคณบดี)',
      'ผศ.ดร.ไซนีย์ ตำภู (รองคณบดี)',
      'ผศ.ดร.ปพน บุษยมาลย์ (รองคณบดี)',
    ],
    displayOrder: 8,
    status: 'ACTIVE',
    isActive: true,
    createdAt: '2026-01-01T00:00:00.000Z',
    createdBy: 'SYSTEM',
    updatedAt: '2026-01-01T00:00:00.000Z',
    updatedBy: 'SYSTEM',
  },
];

export const INITIAL_STRATEGIES: StrategicIssue[] = [
  // Year 2569 (6 Strategic Issues)
  {
    id: 'STRAT-2569-1',
    code: 'ยุทธศาสตร์ที่ 1',
    name: 'ยุทธศาสตร์ที่ 1: การพัฒนาหลักสูตรและการเรียนรู้สู่สากล',
    fiscalYear: '2569',
    objectives: [
      'เพื่อยกระดับหลักสูตรให้ได้รับการรับรองมาตรฐานสากล AUN-QA / EdPEx',
      'เพื่อเพิ่มอัตราการได้งานทำของบัณฑิตและผลสัมฤทธิ์ทางการเรียน',
    ],
  },
  {
    id: 'STRAT-2569-2',
    code: 'ยุทธศาสตร์ที่ 2',
    name: 'ยุทธศาสตร์ที่ 2: การวิจัย นวัตกรรม และนิเวศทางวิชาการ',
    fiscalYear: '2569',
    objectives: [
      'เพื่อเพิ่มจำนวนทุนวิจัยภายนอกและตีพิมพ์ในวารสารระดับชาติ/นานาชาติ Scopus',
      'เพื่อพัฒนาศูนย์ความเป็นเลิศทางวิชาการและการวิจัย',
    ],
  },
  {
    id: 'STRAT-2569-3',
    code: 'ยุทธศาสตร์ที่ 3',
    name: 'ยุทธศาสตร์ที่ 3: บริการวิชาการนวัตกรรมสังคมและศิลปวัฒนธรรม',
    fiscalYear: '2569',
    objectives: [
      'เพื่อขับเคลื่อนโครงการบริการวิชาการสร้างมูลค่าและนวัตกรรมสังคม',
      'เพื่อส่งเสริมการทำนุบำรุงศิลปวัฒนธรรมและภูมิปัญญาท้องถิ่นสู่สากล',
    ],
  },
  {
    id: 'STRAT-2569-4',
    code: 'ยุทธศาสตร์ที่ 4',
    name: 'ยุทธศาสตร์ที่ 4: ความเป็นสากลและเครือข่ายความร่วมมือต่างประเทศ',
    fiscalYear: '2569',
    objectives: [
      'เพื่อเพิ่มจำนวนนิสิตแลกเปลี่ยนและกิจกรรมวิชาการร่วมกับสถาบันต่างประเทศ',
      'เพื่อเสริมสร้างทักษะศตวรรษที่ 21 และสมรรถนะภาษาต่างประเทศ',
    ],
  },
  {
    id: 'STRAT-2569-5',
    code: 'ยุทธศาสตร์ที่ 5',
    name: 'ยุทธศาสตร์ที่ 5: การบริหารจัดการองค์กรดิจิทัลและบุคลากรสมรรถนะสูง',
    fiscalYear: '2569',
    objectives: [
      'เพื่อพัฒนาระบบบริหารจัดการดิจิทัล (Smart HUSO)',
      'เพื่อเพิ่มสัดส่วนอาจารย์ดำรงตำแหน่งทางวิชาการและบุคลากรสมรรถนะสูง',
    ],
  },
  {
    id: 'STRAT-2569-6',
    code: 'ยุทธศาสตร์ที่ 6',
    name: 'ยุทธศาสตร์ที่ 6: ความยั่งยืนทางการเงินและองค์กรสีเขียว',
    fiscalYear: '2569',
    objectives: [
      'เพื่อสร้างความมั่นคงทางการเงินและแสวงหารายได้พึ่งพาตนเองอย่างยั่งยืน',
      'เพื่อบริหารจัดการทรัพยากรและสิ่งแวดล้อมตามแนวทางองค์กรสีเขียว (Green & Sustainable Faculty)',
    ],
  },

  // Year 2570 (5 Strategic Issues)
  {
    id: 'STRAT-2570-1',
    code: 'ยุทธศาสตร์ที่ 1',
    name: 'ยุทธศาสตร์ที่ 1: การยกระดับการศึกษามนุษยศาสตร์ดิจิทัล (Digital Humanities)',
    fiscalYear: '2570',
    objectives: ['ขยายหลักสูตรการเรียนรู้ตลอดชีวิต (Lifelong Learning)'],
  },
  {
    id: 'STRAT-2570-2',
    code: 'ยุทธศาสตร์ที่ 2',
    name: 'ยุทธศาสตร์ที่ 2: งานวิจัยและนวัตกรรมสร้างมูลค่าเชิงพาณิชย์และสังคม',
    fiscalYear: '2570',
    objectives: ['เพื่อสร้างนวัตกรรมมนุษยศาสตร์สู่เชิงพาณิชย์'],
  },
  {
    id: 'STRAT-2570-3',
    code: 'ยุทธศาสตร์ที่ 3',
    name: 'ยุทธศาสตร์ที่ 3: พันธกิจสัมพันธ์เพื่อพัฒนาชุมชนอย่างยั่งยืน (Social Impact)',
    fiscalYear: '2570',
    objectives: ['เพื่อยกระดับรายได้และคุณภาพชีวิตชุมชนรายรอบ'],
  },
  {
    id: 'STRAT-2570-4',
    code: 'ยุทธศาสตร์ที่ 4',
    name: 'ยุทธศาสตร์ที่ 4: เครือข่ายความร่วมมือสากลและหลักสูตรสองปริญญา (Double Degree)',
    fiscalYear: '2570',
    objectives: ['เพิ่มหลักสูตรนานาชาติและความร่วมมือร่วมกับต่างประเทศ'],
  },
  {
    id: 'STRAT-2570-5',
    code: 'ยุทธศาสตร์ที่ 5',
    name: 'ยุทธศาสตร์ที่ 5: ธรรมาภิบาลและการบริหารองค์กรสมรรถนะสูง',
    fiscalYear: '2570',
    objectives: ['มุ่งสู่การเป็นคณะยอดเยี่ยมด้วยระบบ EdPEx 300'],
  },

  // Year 2571 (4 Strategic Issues)
  {
    id: 'STRAT-2571-1',
    code: 'ยุทธศาสตร์ที่ 1',
    name: 'ยุทธศาสตร์ที่ 1: การจัดการศึกษาไร้พรมแดน (Global Online Education)',
    fiscalYear: '2571',
    objectives: ['เปิดการสอน Micro-credentials ระดับสากล'],
  },
  {
    id: 'STRAT-2571-2',
    code: 'ยุทธศาสตร์ที่ 2',
    name: 'ยุทธศาสตร์ที่ 2: นิเวศการวิจัยและศูนย์ปัญญาประดิษฐ์ทางสังคมศาสตร์',
    fiscalYear: '2571',
    objectives: ['ประยุกต์ AI เพื่อวิจัยด้านมนุษยศาสตร์และภาษาศาสตร์'],
  },
  {
    id: 'STRAT-2571-3',
    code: 'ยุทธศาสตร์ที่ 3',
    name: 'ยุทธศาสตร์ที่ 3: การขับเคลื่อนเศรษฐกิจสร้างสรรค์และทุนทางวัฒนธรรม',
    fiscalYear: '2571',
    objectives: ['ผลักดัน Soft Power สู่ระดับโลก'],
  },
  {
    id: 'STRAT-2571-4',
    code: 'ยุทธศาสตร์ที่ 4',
    name: 'ยุทธศาสตร์ที่ 4: การบริหารจัดการและพัฒนาองค์กรอัจฉริยะ (Smart Faculty)',
    fiscalYear: '2571',
    objectives: ['ระบบอัตโนมัติและการบริหารทรัพยากรบุคคลชั้นนำ'],
  },
];

export const THAI_MONTHS = [
  { id: 1, name: 'ตุลาคม', short: 'ต.ค.', quarter: 'Q1' },
  { id: 2, name: 'พฤศจิกายน', short: 'พ.ย.', quarter: 'Q1' },
  { id: 3, name: 'ธันวาคม', short: 'ธ.ค.', quarter: 'Q1' },
  { id: 4, name: 'มกราคม', short: 'ม.ค.', quarter: 'Q2' },
  { id: 5, name: 'กุมภาพันธ์', short: 'ก.พ.', quarter: 'Q2' },
  { id: 6, name: 'มีนาคม', short: 'มี.ค.', quarter: 'Q2' },
  { id: 7, name: 'เมษายน', short: 'เม.ย.', quarter: 'Q3' },
  { id: 8, name: 'พฤษภาคม', short: 'พ.ค.', quarter: 'Q3' },
  { id: 9, name: 'มิถุนายน', short: 'มิ.ย.', quarter: 'Q3' },
  { id: 10, name: 'กรกฎาคม', short: 'ก.ค.', quarter: 'Q4' },
  { id: 11, name: 'สิงหาคม', short: 'ส.ค.', quarter: 'Q4' },
  { id: 12, name: 'กันยายน', short: 'ก.ย.', quarter: 'Q4' },
];

export const EVALUATION_ROUNDS = [
  { id: 'ALL', name: 'ทุกรอบระยะเวลา (3, 6, 9 เดือน & 1 ปี)', code: 'ทุกรอบ', monthEnd: 12 },
  { id: '3M', name: 'รอบ 3 เดือน (ไตรมาส 1: ต.ค. - ธ.ค.)', code: 'รอบ 3 เดือน', monthEnd: 3 },
  { id: '6M', name: 'รอบ 6 เดือน (ไตรมาส 2 / ครึ่งปี: ต.ค. - มี.ค.)', code: 'รอบ 6 เดือน', monthEnd: 6 },
  { id: '9M', name: 'รอบ 9 เดือน (ไตรมาส 3: ต.ค. - มิ.ย.)', code: 'รอบ 9 เดือน', monthEnd: 9 },
  { id: '1Y', name: 'รอบ 1 ปี (12 เดือน / สิ้นปีงบประมาณ: ต.ค. - ก.ย.)', code: 'รอบ 1 ปี', monthEnd: 12 },
];

export const INITIAL_CONFIG: SystemConfig = {
  scoreCap: 120,
  thresholds: {
    onTrack: 100,
    watch: 85,
    risk: 70,
    critical: 0,
  },
  defaultFiscalYear: '2569',
  notificationEmail: 'huso-kpi@huso.edu.th',
  autoReportDayOfMonth: 30,
};

export const INITIAL_USERS: User[] = [
  {
    userId: 'U-001',
    email: 'sawaporn.c@huso.edu.th',
    fullName: 'ผศ.สวพร จันทรสกุล (คณบดี)',
    role: 'EXECUTIVE',
    rolesDisplay: 'EXECUTIVE / ADMIN / REVIEWER',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-002',
    email: 'chonticha.s@huso.edu.th',
    fullName: 'อ.ชลธิชา สุรัตนสัญญา (รองคณบดี)',
    role: 'REVIEWER',
    rolesDisplay: 'OWNER / REVIEWER',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-003',
    email: 'sainey.t@huso.edu.th',
    fullName: 'ผศ.ดร.ไซนีย์ ตำภู (รองคณบดี)',
    role: 'REVIEWER',
    rolesDisplay: 'OWNER / REVIEWER',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-004',
    email: 'papon.b@huso.edu.th',
    fullName: 'ผศ.ดร.ปพน บุษยมาลย์ (รองคณบดี)',
    role: 'REVIEWER',
    rolesDisplay: 'OWNER / REVIEWER',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-005',
    email: 'qa.staff@huso.edu.th',
    fullName: 'งานประกันคุณภาพ (เจ้าหน้าที่)',
    role: 'OWNER',
    rolesDisplay: 'OWNER',
    departmentId: 'DEP-005',
    departmentName: 'งานประกันคุณภาพการศึกษา',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-006',
    email: 'student.staff@huso.edu.th',
    fullName: 'งานพัฒนานักศึกษา (เจ้าหน้าที่)',
    role: 'OWNER',
    rolesDisplay: 'OWNER',
    departmentId: 'DEP-002',
    departmentName: 'งานพัฒนานักศึกษา',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-007',
    email: 'academic.staff@huso.edu.th',
    fullName: 'งานวิชาการ (เจ้าหน้าที่)',
    role: 'OWNER',
    rolesDisplay: 'OWNER',
    departmentId: 'DEP-001',
    departmentName: 'งานวิชาการ',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-008',
    email: 'research.staff@huso.edu.th',
    fullName: 'งานวิจัยและพัฒนาท้องถิ่น (เจ้าหน้าที่)',
    role: 'OWNER',
    rolesDisplay: 'OWNER',
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-009',
    email: 'culture.staff@huso.edu.th',
    fullName: 'งานศิลปะและวัฒนธรรม (เจ้าหน้าที่)',
    role: 'OWNER',
    rolesDisplay: 'OWNER',
    departmentId: 'DEP-004',
    departmentName: 'งานศิลปะและวัฒนธรรม',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
  },
  {
    userId: 'U-010',
    email: 'staff@huso.edu.th',
    fullName: 'งานสำนักงานคณบดี (เจ้าหน้าที่)',
    role: 'VIEWER',
    rolesDisplay: 'VIEWER',
    departmentId: 'DEP-007',
    departmentName: 'งานสำนักงานคณบดี',
    avatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_INDICATORS: Indicator[] = [
  // Default KVIs from Prompt Section 9
  {
    indicatorId: 'IND-KVI-01',
    code: 'KVI-2569-001',
    type: 'KVI',
    name: 'KVI 1: จำนวนหลักสูตรที่ได้รับการรับรองมาตรฐานสากล (AUN-QA / EdPEx)',
    description: 'หลักสูตรระดับปริญญาตรีและบัณฑิตศึกษาของคณะที่ผ่านการประเมินคุณภาพมาตรฐานระดับสากล',
    operationalDef: 'นับรวมหลักสูตรที่ได้รับใบรับรองมาตรฐานการศึกษา AUN-QA หรือผ่านการประเมิน EdPEx 200',
    vision: 'มุ่งสู่คณะมนุษยศาสตร์และสังคมศาสตร์ชั้นนำระดับภูมิภาคอาเซียน',
    strategyId: 'STRAT-2569-1',
    strategyName: 'ยุทธศาสตร์ที่ 1',
    objective: 'ยกระดับมาตรฐานหลักสูตรเทียบเท่าสากล',
    strategy: 'ปรับปรุงหลักสูตรอิงผลลัพธ์ (OBE) และรับการประเมินจากองค์กรภายนอก',
    mission: 'การผลิตบัณฑิต',
    unit: 'หลักสูตร',
    direction: 'MORE_IS_BETTER',
    formula: 'ผลรวมหลักสูตรที่ได้รับการรับรองสะสม',
    source: 'รายงานผลการประเมินประกันคุณภาพการศึกษา งานประกันคุณภาพ',
    frequency: 'ANNUAL',
    baseline: 2,
    ownerMain: 'ผศ.สวพร จันทรสกุล',
    ownerCo: 'ประธานหลักสูตรทุกหลักสูตร',
    primaryOwnerId: 'PER-0001',
    primaryOwnerName: 'ผศ.สวพร จันทรสกุล',
    primaryOwnerPosition: 'คณบดี',
    dataSupporterIds: ['PER-0010', 'PER-0005'],
    dataSupporters: [
      { personnelId: 'PER-0010', fullName: 'น.ส.ปิยะมาศ สร้อยแก้ว', role: 'ผู้สนับสนุนข้อมูล' },
      { personnelId: 'PER-0005', fullName: 'นายเลิศยศ เผื่ออำนาจ', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-005',
    responsibleDepartmentName: 'งานประกันคุณภาพการศึกษา',
    coResponsibleDepartmentIds: ['DEP-001'],
    coResponsibleDepartments: [{ departmentId: 'DEP-001', departmentName: 'งานวิชาการ' }],
    departmentId: 'DEP-005',
    departmentName: 'งานประกันคุณภาพการศึกษา',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 25,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    remarks: 'เป้าหมายสี่ปี: 2569=3, 2570=5, 2571=7, 2572=10',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KVI-02',
    code: 'KVI-2569-002',
    type: 'KVI',
    name: 'KVI 2: จำนวนศูนย์ความเป็นเลิศทางวิชาการและวิจัยระดับชาติ/นานาชาติ',
    description: 'ศูนย์วิจัยและนวัตกรรมทางสังคมศาสตร์ที่ได้รับการจัดตั้งและรับรองโดยมหาวิทยาลัย',
    operationalDef: 'ศูนย์วิจัยที่มีผลงานตีพิมพ์ ตีตอบโจทย์แก้ปัญหาชุมชน และมีงบประมาณสนับสนุนต่อเนื่อง',
    vision: 'ขุมปัญญาแห่งมนุษยศาสตร์และสังคมศาสตร์เพื่อการพัฒนาอย่างยั่งยืน',
    strategyId: 'STRAT-2569-2',
    strategyName: 'ยุทธศาสตร์ที่ 2',
    objective: 'สร้างนิเวศการวิจัยเข้มแข็ง',
    strategy: 'สนับสนุนการรวมกลุ่มนักวิจัยสร้าง Center of Excellence',
    mission: 'การวิจัยและนวัตกรรม',
    unit: 'ศูนย์',
    direction: 'MORE_IS_BETTER',
    formula: 'จำนวนศูนย์ความเป็นเลิศที่เปิดดำเนินการและสร้างผลกระทบ',
    source: 'งานวิจัยและพัฒนาท้องถิ่น',
    frequency: 'ANNUAL',
    baseline: 1,
    ownerMain: 'ผศ.ดร.ไซนีย์ ตำภู',
    ownerCo: 'หัวหน้าศูนย์วิจัย',
    primaryOwnerId: 'PER-0003',
    primaryOwnerName: 'ผศ.ดร.ไซนีย์ ตำภู',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0008'],
    dataSupporters: [
      { personnelId: 'PER-0008', fullName: 'น.ส.ศศิธร อินน้ำหอม', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-003',
    responsibleDepartmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    coResponsibleDepartmentIds: ['DEP-008'],
    coResponsibleDepartments: [{ departmentId: 'DEP-008', departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)' }],
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 25,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    remarks: 'เป้าหมายสี่ปี: 2569=2, 2570=3, 2571=4, 2572=5',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KVI-03',
    code: 'KVI-2569-003',
    type: 'KVI',
    name: 'KVI 3: ร้อยละของอาจารย์ที่มีตำแหน่งทางวิชาการระดับ ผศ./รศ./ศ.',
    description: 'สัดส่วนอาจารย์ประจำคณะที่ดำรงตำแหน่งทางวิชาการเทียบกับอาจารย์ประจำทั้งหมด',
    operationalDef: '(จำนวนอาจารย์ดำรงตำแหน่ง ผศ.+รศ.+ศ. / จำนวนอาจารย์ประจำทั้งหมด) * 100',
    vision: 'องค์กรแห่งการเรียนรู้และสร้างสรรค์ปัญญา',
    strategyId: 'STRAT-2569-5',
    strategyName: 'ยุทธศาสตร์ที่ 5',
    objective: 'พัฒนาศักยภาพอาจารย์สู่วิชาการชั้นนำ',
    strategy: 'มีระบบ Fast-track และคลินิกการขอตำแหน่งทางวิชาการ',
    mission: 'การบริหารองค์กร',
    unit: 'ร้อยละ',
    direction: 'MORE_IS_BETTER',
    formula: '(อาจารย์มีตำแหน่งทางวิชาการ ÷ อาจารย์ทั้งหมด) × 100',
    source: 'งานบริหาร บุคคล และการเงิน',
    frequency: 'QUARTERLY',
    baseline: 8.5,
    ownerMain: 'ผศ.ดร.ปพน บุษยมาลย์',
    ownerCo: 'งานบริหาร บุคคล และการเงิน',
    primaryOwnerId: 'PER-0004',
    primaryOwnerName: 'ผศ.ดร.ปพน บุษยมาลย์',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0011'],
    dataSupporters: [
      { personnelId: 'PER-0011', fullName: 'นายชนินทร์ มาทวี', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-006',
    responsibleDepartmentName: 'งานบริหาร บุคคล และการเงิน',
    coResponsibleDepartmentIds: ['DEP-008'],
    coResponsibleDepartments: [{ departmentId: 'DEP-008', departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)' }],
    departmentId: 'DEP-006',
    departmentName: 'งานบริหาร บุคคล และการเงิน',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 25,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    remarks: 'เป้าหมายสี่ปี: 2569=10%, 2570=12%, 2571=15%, 2572=20%',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KVI-04',
    code: 'KVI-2569-004',
    type: 'KVI',
    name: 'KVI 4: จำนวนนวัตกรรมทางสังคมหรือผลงานสร้างสรรค์ที่นำไปใช้ประโยชน์เชิงพื้นที่',
    description: 'ผลงานวิจัย นวัตกรรมสังคม หรือผลงานสร้างสรรค์ทางศิลปวัฒนธรรมที่เกิดการนำไปใช้จริงในชุมชน',
    operationalDef: 'นับเฉพาะผลงานที่มีหนังสือรับรองการนำไปใช้ประโยชน์เชิงพื้นที่ ชุมชน หรือเชิงพาณิชย์',
    vision: 'สร้างคุณค่าเชิงสังคมและยกระดับชุมชน',
    strategyId: 'STRAT-2569-3',
    strategyName: 'ยุทธศาสตร์ที่ 3',
    objective: 'ขยายผลบริการวิชาการสู่นวัตกรรมสังคม',
    strategy: 'เชื่อมโยงภาคีเครือข่ายชุมชน ร่วมสร้างโซลูชันเพื่อพื้นที่',
    mission: 'การบริการวิชาการ',
    unit: 'ผลงาน',
    direction: 'MORE_IS_BETTER',
    formula: 'จำนวนผลงานนวัตกรรมสังคมที่มีหนังสือรับรองการใช้งานจริง',
    source: 'งานวิจัยและพัฒนาท้องถิ่น',
    frequency: 'ANNUAL',
    baseline: 0,
    ownerMain: 'อ.ชลธิชา สุรัตนสัญญา',
    ownerCo: 'งานวิจัยและพัฒนาท้องถิ่น',
    primaryOwnerId: 'PER-0002',
    primaryOwnerName: 'อ.ชลธิชา สุรัตนสัญญา',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0008', 'PER-0009'],
    dataSupporters: [
      { personnelId: 'PER-0008', fullName: 'น.ส.ศศิธร อินน้ำหอม', role: 'ผู้สนับสนุนข้อมูล' },
      { personnelId: 'PER-0009', fullName: 'น.ส.จิรชยา ฉวีอินทร์', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-003',
    responsibleDepartmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    coResponsibleDepartmentIds: ['DEP-004'],
    coResponsibleDepartments: [{ departmentId: 'DEP-004', departmentName: 'งานศิลปะและวัฒนธรรม' }],
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 25,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    remarks: 'เป้าหมายสี่ปี: 2569=1, 2570=2, 2571=3, 2572=4',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },

  // Standard KPIs
  {
    indicatorId: 'IND-KPI-01',
    code: 'KPI-2569-001',
    type: 'KPI',
    name: 'ร้อยละของบัณฑิตปริญญาตรีที่ได้งานทำหรือประกอบอาชีพอิสระภายใน 1 ปี',
    description: 'สำรวจข้อมูลภาวการณ์มีงานทำของบัณฑิตรุ่นปีการศึกษาที่ผ่านมา',
    operationalDef: '(จำนวนบัณฑิตที่ได้งานทำหรือประกอบอาชีพอิสระ / บัณฑิตที่ตอบแบบสำรวจ) * 100',
    vision: 'บัณฑิตมีสมรรถนะพร้อมทำงานสอดคล้องกับตลาดแรงงานยุคใหม่',
    strategyId: 'STRAT-2569-1',
    strategyName: 'ยุทธศาสตร์ที่ 1',
    objective: 'บัณฑิตมีอัตราการได้งานทำสูง',
    strategy: 'จัดกิจกรรมเตรียมความพร้อมอาชีพและการฝึกประสบการณ์วิชาชีพเข้มข้น',
    mission: 'การผลิตบัณฑิต',
    unit: 'ร้อยละ',
    direction: 'MORE_IS_BETTER',
    formula: '(บัณฑิตได้งานทำ ÷ บัณฑิตตอบแบบสำรวจ) × 100',
    source: 'ระบบสำรวจภาวการณ์มีงานทำ งานพัฒนานักศึกษา',
    frequency: 'ANNUAL',
    baseline: 82.5,
    ownerMain: 'อ.ชลธิชา สุรัตนสัญญา',
    primaryOwnerId: 'PER-0002',
    primaryOwnerName: 'อ.ชลธิชา สุรัตนสัญญา',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0007', 'PER-0005'],
    dataSupporters: [
      { personnelId: 'PER-0007', fullName: 'น.ส.บุษรอ นิโลง', role: 'ผู้สนับสนุนข้อมูล' },
      { personnelId: 'PER-0005', fullName: 'นายเลิศยศ เผื่ออำนาจ', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-002',
    responsibleDepartmentName: 'งานพัฒนานักศึกษา',
    coResponsibleDepartmentIds: ['DEP-001'],
    coResponsibleDepartments: [{ departmentId: 'DEP-001', departmentName: 'งานวิชาการ' }],
    departmentId: 'DEP-002',
    departmentName: 'งานพัฒนานักศึกษา',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 20,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KPI-02',
    code: 'KPI-2569-002',
    type: 'KPI',
    name: 'จำนวนบทความวิจัยที่ได้รับการตีพิมพ์ในวารสารระดับนานาชาติฐาน Scopus / Web of Science',
    description: 'ผลงานวิจัยของอาจารย์และนักวิจัยประจำคณะมนุษยศาสตร์ฯ ที่ตีพิมพ์ในฐานนานาชาติ',
    operationalDef: 'นับบทความที่เผยแพร่และมีชื่อสถาบันคณะมนุษยศาสตร์และสังคมศาสตร์',
    vision: 'การวิจัยเป็นที่ยอมรับระดับสากล',
    strategyId: 'STRAT-2569-2',
    strategyName: 'ยุทธศาสตร์ที่ 2',
    objective: 'สร้างผลงานวิจัยคุณภาพสูง',
    strategy: 'อุดหนุนค่าตีพิมพ์และรางวัลสร้างขวัญกำลังใจแก่นักวิจัย',
    mission: 'การวิจัยและนวัตกรรม',
    unit: 'บทความ',
    direction: 'MORE_IS_BETTER',
    formula: 'ผลรวมจำนวนบทความวิจัยตีพิมพ์สะสม',
    source: 'งานวิจัยและพัฒนาท้องถิ่น คณะมนุษยศาสตร์ฯ',
    frequency: 'MONTHLY',
    baseline: 12,
    ownerMain: 'ผศ.ดร.ไซนีย์ ตำภู',
    primaryOwnerId: 'PER-0003',
    primaryOwnerName: 'ผศ.ดร.ไซนีย์ ตำภู',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0008'],
    dataSupporters: [
      { personnelId: 'PER-0008', fullName: 'น.ส.ศศิธร อินน้ำหอม', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-003',
    responsibleDepartmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    coResponsibleDepartmentIds: ['DEP-008'],
    coResponsibleDepartments: [{ departmentId: 'DEP-008', departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)' }],
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 20,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KPI-03',
    code: 'KPI-2569-003',
    type: 'KPI',
    name: 'จำนวนโครงการบริการวิชาการที่สร้างรายได้หรือมูลค่าเพิ่มแก่ชุมชน',
    description: 'โครงการให้บริการวิชาการที่บูรณาการกับการเรียนการสอนและการวิจัย',
    operationalDef: 'โครงการที่มีการประเมินผลกระทบทางเศรษฐกิจหรือสังคม (SROI / Social Impact)',
    vision: 'การบริการวิชาการชี้นำสังคม',
    strategyId: 'STRAT-2569-3',
    strategyName: 'ยุทธศาสตร์ที่ 3',
    objective: 'ให้บริการวิชาการคุณค่าสูง',
    strategy: 'ส่งเสริมโครงการ 1 หลักสูตร 1 ชุมชนนวัตกรรม',
    mission: 'การบริการวิชาการ',
    unit: 'โครงการ',
    direction: 'MORE_IS_BETTER',
    formula: 'จำนวนโครงการที่บรรลุเป้าหมายสร้างมูลค่าเพิ่ม',
    source: 'งานวิจัยและพัฒนาท้องถิ่น',
    frequency: 'QUARTERLY',
    baseline: 5,
    ownerMain: 'ผศ.ดร.ไซนีย์ ตำภู',
    primaryOwnerId: 'PER-0003',
    primaryOwnerName: 'ผศ.ดร.ไซนีย์ ตำภู',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0008', 'PER-0009'],
    dataSupporters: [
      { personnelId: 'PER-0008', fullName: 'น.ส.ศศิธร อินน้ำหอม', role: 'ผู้สนับสนุนข้อมูล' },
      { personnelId: 'PER-0009', fullName: 'น.ส.จิรชยา ฉวีอินทร์', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-003',
    responsibleDepartmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    coResponsibleDepartmentIds: ['DEP-004'],
    coResponsibleDepartments: [{ departmentId: 'DEP-004', departmentName: 'งานศิลปะและวัฒนธรรม' }],
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 20,
    priority: 'MEDIUM',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KPI-04',
    code: 'KPI-2569-004',
    type: 'KPI',
    name: 'จำนวนโครงการทำนุบำรุงศิลปะและวัฒนธรรมที่ได้รับการเผยแพร่ระดับชาติ/นานาชาติ',
    description: 'การอนุรักษ์ ฟื้นฟู และต่อยอดทุนทางวัฒนธรรมและภูมิปัญญาท้องถิ่น',
    operationalDef: 'นิทรรศการ การแสดง หรืองานสร้างสรรค์ที่เผยแพร่สู่สาธารณะ',
    vision: 'ทำนุบำรุงศิลปวัฒนธรรมด้วยนวัตกรรมความคิดสร้างสรรค์',
    strategyId: 'STRAT-2569-3',
    strategyName: 'ยุทธศาสตร์ที่ 3',
    objective: 'เผยแพร่วัฒนธรรมไทยสู่สากล',
    strategy: 'จัดเทศกาลวัฒนธรรมและนิทรรศการสร้างสรรค์ร่วมกับภาคี',
    mission: 'การทำนุบำรุงศิลปะและวัฒนธรรม',
    unit: 'โครงการ',
    direction: 'MORE_IS_BETTER',
    formula: 'จำนวนโครงการทำนุบำรุงศิลปวัฒนธรรมที่ดำเนินการแล้วเสร็จ',
    source: 'งานศิลปะและวัฒนธรรม',
    frequency: 'QUARTERLY',
    baseline: 4,
    ownerMain: 'อ.ชลธิชา สุรัตนสัญญา',
    primaryOwnerId: 'PER-0002',
    primaryOwnerName: 'อ.ชลธิชา สุรัตนสัญญา',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0009'],
    dataSupporters: [
      { personnelId: 'PER-0009', fullName: 'น.ส.จิรชยา ฉวีอินทร์', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-004',
    responsibleDepartmentName: 'งานศิลปะและวัฒนธรรม',
    coResponsibleDepartmentIds: ['DEP-003'],
    coResponsibleDepartments: [{ departmentId: 'DEP-003', departmentName: 'งานวิจัยและพัฒนาท้องถิ่น' }],
    departmentId: 'DEP-004',
    departmentName: 'งานศิลปะและวัฒนธรรม',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 20,
    priority: 'MEDIUM',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KPI-05',
    code: 'KPI-2569-005',
    type: 'KPI',
    name: 'จำนวนนิสิตที่เข้าร่วมโครงการแลกเปลี่ยนหรือกิจกรรมวิชาการต่างประเทศ',
    description: 'นิสิตที่ได้รับการสนับสนุนทุนแลกเปลี่ยนหรือเข้าร่วมสัมมนาระดับสากล',
    operationalDef: 'จำนวนคน/ครั้ง ของนิสิตที่ร่วมกิจกรรมวิชาการในต่างประเทศหรือโปรแกรมออนไลน์สากล',
    vision: 'สร้างความเป็นสากลแก่นิสิต',
    strategyId: 'STRAT-2569-4',
    strategyName: 'ยุทธศาสตร์ที่ 4',
    objective: 'เพิ่มโอกาสแลกเปลี่ยนต่างประเทศ',
    strategy: 'ลงนาม MoU กับมหาวิทยาลัยต่างประเทศและจัดทุนสนับสนุนนิสิต',
    mission: 'การพัฒนานิสิต',
    unit: 'คน',
    direction: 'MORE_IS_BETTER',
    formula: 'ผลรวมจำนวนนิสิตเข้าร่วมกิจกรรมสากล',
    source: 'งานวิชาการและวิเทศสัมพันธ์',
    frequency: 'MONTHLY',
    baseline: 8,
    ownerMain: 'ผศ.สวพร จันทรสกุล',
    primaryOwnerId: 'PER-0001',
    primaryOwnerName: 'ผศ.สวพร จันทรสกุล',
    primaryOwnerPosition: 'คณบดี',
    dataSupporterIds: ['PER-0005', 'PER-0006'],
    dataSupporters: [
      { personnelId: 'PER-0005', fullName: 'นายเลิศยศ เผื่ออำนาจ', role: 'ผู้สนับสนุนข้อมูล' },
      { personnelId: 'PER-0006', fullName: 'นายชลธิวัฒน์ นุ้ยไกร', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-001',
    responsibleDepartmentName: 'งานวิชาการ',
    coResponsibleDepartmentIds: ['DEP-002', 'DEP-007'],
    coResponsibleDepartments: [
      { departmentId: 'DEP-002', departmentName: 'งานพัฒนานักศึกษา' },
      { departmentId: 'DEP-007', departmentName: 'งานสำนักงานคณบดี' },
    ],
    departmentId: 'DEP-001',
    departmentName: 'งานวิชาการ',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 20,
    priority: 'HIGH',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    indicatorId: 'IND-KPI-06',
    code: 'KPI-2569-006',
    type: 'KPI',
    name: 'ระยะเวลาเฉลี่ยในการเบิกจ่ายงบประมาณโครงการให้เป็นไปตามแผน (Less is Better)',
    description: 'วัดความรวดเร็วและประสิทธิภาพในการดำเนินกระบวนการจัดซื้อจัดจ้างและเบิกจ่าย',
    operationalDef: 'จำนวนวันเฉลี่ยตั้งแต่ได้รับอนุมัติโครงการจนถึงเบิกจ่ายเงินสำเร็จ',
    vision: 'การบริหารจัดการรวดเร็ว โปร่งใส มีประสิทธิภาพ',
    strategyId: 'STRAT-2569-5',
    strategyName: 'ยุทธศาสตร์ที่ 5',
    objective: 'ลดระยะเวลากระบวนการทำงาน',
    strategy: 'นำระบบอนุมัติอิเล็กทรอนิกส์ E-Budgeting มาใช้อย่างเต็มรูปแบบ',
    mission: 'การบริหารองค์กร',
    unit: 'วัน',
    direction: 'LESS_IS_BETTER',
    formula: '(เป้าหมายจำนวนวัน ÷ จำนวนวันจริงที่ใช้) × 100',
    source: 'งานบริหาร บุคคล และการเงิน',
    frequency: 'MONTHLY',
    baseline: 14,
    ownerMain: 'ผศ.ดร.ปพน บุษยมาลย์',
    primaryOwnerId: 'PER-0004',
    primaryOwnerName: 'ผศ.ดร.ปพน บุษยมาลย์',
    primaryOwnerPosition: 'รองคณบดี',
    dataSupporterIds: ['PER-0011'],
    dataSupporters: [
      { personnelId: 'PER-0011', fullName: 'นายชนินทร์ มาทวี', role: 'ผู้สนับสนุนข้อมูล' },
    ],
    responsibleDepartmentId: 'DEP-006',
    responsibleDepartmentName: 'งานบริหาร บุคคล และการเงิน',
    coResponsibleDepartmentIds: ['DEP-007'],
    coResponsibleDepartments: [{ departmentId: 'DEP-007', departmentName: 'งานสำนักงานคณบดี' }],
    departmentId: 'DEP-006',
    departmentName: 'งานบริหาร บุคคล และการเงิน',
    mappingStatus: 'MAPPED',
    startDate: '2025-10-01',
    endDate: '2026-09-30',
    weight: 15,
    priority: 'MEDIUM',
    isActive: true,
    status: 'ACTIVE',
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
];

export const INITIAL_TARGETS: Target[] = [
  // Targets for 2569
  {
    targetId: 'TGT-KVI-01-2569',
    indicatorId: 'IND-KVI-01',
    fiscalYear: '2569',
    annualTarget: 3,
    minTarget: 2,
    challengeTarget: 4,
    baseline: 2,
    q1Target: 2,
    q2Target: 2,
    q3Target: 3,
    q4Target: 3,
    monthlyTargets: [2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
    cumulativeTargets: [2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3],
  },
  {
    targetId: 'TGT-KVI-02-2569',
    indicatorId: 'IND-KVI-02',
    fiscalYear: '2569',
    annualTarget: 2,
    minTarget: 1,
    challengeTarget: 3,
    baseline: 1,
    q1Target: 1,
    q2Target: 1,
    q3Target: 2,
    q4Target: 2,
    monthlyTargets: [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
    cumulativeTargets: [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2],
  },
  {
    targetId: 'TGT-KVI-03-2569',
    indicatorId: 'IND-KVI-03',
    fiscalYear: '2569',
    annualTarget: 10.0,
    minTarget: 9.0,
    challengeTarget: 12.0,
    baseline: 8.5,
    q1Target: 8.8,
    q2Target: 9.2,
    q3Target: 9.6,
    q4Target: 10.0,
    monthlyTargets: [8.6, 8.7, 8.8, 8.9, 9.0, 9.2, 9.4, 9.6, 9.8, 9.9, 10.0, 10.0],
    cumulativeTargets: [8.6, 8.7, 8.8, 8.9, 9.0, 9.2, 9.4, 9.6, 9.8, 9.9, 10.0, 10.0],
  },
  {
    targetId: 'TGT-KVI-04-2569',
    indicatorId: 'IND-KVI-04',
    fiscalYear: '2569',
    annualTarget: 1,
    minTarget: 1,
    challengeTarget: 2,
    baseline: 0,
    q1Target: 0,
    q2Target: 0,
    q3Target: 1,
    q4Target: 1,
    monthlyTargets: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
    cumulativeTargets: [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
  },

  {
    targetId: 'TGT-KPI-01-2569',
    indicatorId: 'IND-KPI-01',
    fiscalYear: '2569',
    annualTarget: 85.0,
    minTarget: 80.0,
    challengeTarget: 90.0,
    baseline: 82.5,
    q1Target: 83.0,
    q2Target: 84.0,
    q3Target: 85.0,
    q4Target: 85.0,
    monthlyTargets: [83, 83, 83, 84, 84, 84, 85, 85, 85, 85, 85, 85],
    cumulativeTargets: [83, 83, 83, 84, 84, 84, 85, 85, 85, 85, 85, 85],
  },
  {
    targetId: 'TGT-KPI-02-2569',
    indicatorId: 'IND-KPI-02',
    fiscalYear: '2569',
    annualTarget: 18,
    minTarget: 15,
    challengeTarget: 22,
    baseline: 12,
    q1Target: 4,
    q2Target: 8,
    q3Target: 13,
    q4Target: 18,
    monthlyTargets: [1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1],
    cumulativeTargets: [1, 2, 4, 5, 6, 8, 10, 12, 14, 16, 17, 18],
  },
  {
    targetId: 'TGT-KPI-03-2569',
    indicatorId: 'IND-KPI-03',
    fiscalYear: '2569',
    annualTarget: 8,
    minTarget: 6,
    challengeTarget: 10,
    baseline: 5,
    q1Target: 2,
    q2Target: 4,
    q3Target: 6,
    q4Target: 8,
    monthlyTargets: [0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0],
    cumulativeTargets: [0, 1, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8],
  },
  {
    targetId: 'TGT-KPI-04-2569',
    indicatorId: 'IND-KPI-04',
    fiscalYear: '2569',
    annualTarget: 6,
    minTarget: 4,
    challengeTarget: 8,
    baseline: 4,
    q1Target: 1,
    q2Target: 3,
    q3Target: 4,
    q4Target: 6,
    monthlyTargets: [0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0],
    cumulativeTargets: [0, 0, 1, 2, 3, 3, 4, 4, 5, 5, 6, 6],
  },
  {
    targetId: 'TGT-KPI-05-2569',
    indicatorId: 'IND-KPI-05',
    fiscalYear: '2569',
    annualTarget: 15,
    minTarget: 10,
    challengeTarget: 20,
    baseline: 8,
    q1Target: 3,
    q2Target: 7,
    q3Target: 11,
    q4Target: 15,
    monthlyTargets: [1, 1, 1, 2, 2, 0, 2, 2, 0, 2, 1, 1],
    cumulativeTargets: [1, 2, 3, 5, 7, 7, 9, 11, 11, 13, 14, 15],
  },
  {
    targetId: 'TGT-KPI-06-2569',
    indicatorId: 'IND-KPI-06',
    fiscalYear: '2569',
    annualTarget: 10, // Less is better: Target = 10 days
    minTarget: 12,
    challengeTarget: 7,
    baseline: 14,
    q1Target: 12,
    q2Target: 11,
    q3Target: 10,
    q4Target: 10,
    monthlyTargets: [12, 12, 12, 11, 11, 11, 10, 10, 10, 10, 10, 10],
    cumulativeTargets: [12, 12, 12, 11, 11, 11, 10, 10, 10, 10, 10, 10],
  },
];

export const INITIAL_PROGRESS: MonthlyProgress[] = [];

export const INITIAL_EVIDENCE: Evidence[] = [];

export const INITIAL_DIRECTIVES: ActionDirective[] = [];

export const INITIAL_LOGS: ActivityLog[] = [];

export const INITIAL_REPORTS: MonthlyReport[] = [];

export const INITIAL_PERSONNEL: Personnel[] = [
  {
    personnelId: 'PER-0001',
    fullName: 'ผศ.สวพร จันทรสกุล',
    position: 'คณบดี',
    administrativePosition: 'คณบดี',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    role: 'ผู้บริหาร',
    personnelGroup: 'ผู้บริหาร',
    email: 'jsawaporn@gmail.com',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0002',
    fullName: 'อ.ชลธิชา สุรัตนสัญญา',
    position: 'รองคณบดี',
    administrativePosition: 'รองคณบดี',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    role: 'ผู้บริหาร',
    personnelGroup: 'ผู้บริหาร',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0003',
    fullName: 'ผศ.ดร.ไซนีย์ ตำภู',
    position: 'รองคณบดี',
    administrativePosition: 'รองคณบดี',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    role: 'ผู้บริหาร',
    personnelGroup: 'ผู้บริหาร',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0004',
    fullName: 'ผศ.ดร.ปพน บุษยมาลย์',
    position: 'รองคณบดี',
    administrativePosition: 'รองคณบดี',
    departmentId: 'DEP-008',
    departmentName: 'กลุ่มผู้บริหารคณะ (คณบดี/รองคณบดี)',
    role: 'ผู้บริหาร',
    personnelGroup: 'ผู้บริหาร',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0005',
    fullName: 'นายเลิศยศ เผื่ออำนาจ',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-001',
    departmentName: 'งานวิชาการ',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0006',
    fullName: 'นายชลธิวัฒน์ นุ้ยไกร',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-001',
    departmentName: 'งานวิชาการ',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0007',
    fullName: 'น.ส.บุษรอ นิโลง',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-002',
    departmentName: 'งานพัฒนานักศึกษา',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0008',
    fullName: 'น.ส.ศศิธร อินน้ำหอม',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-003',
    departmentName: 'งานวิจัยและพัฒนาท้องถิ่น',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0009',
    fullName: 'น.ส.จิรชยา ฉวีอินทร์',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-004',
    departmentName: 'งานศิลปะและวัฒนธรรม',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0010',
    fullName: 'น.ส.ปิยะมาศ สร้อยแก้ว',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-005',
    departmentName: 'งานประกันคุณภาพการศึกษา',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    personnelId: 'PER-0011',
    fullName: 'นายชนินทร์ มาทวี',
    position: 'ผู้สนับสนุนข้อมูล',
    administrativePosition: '',
    departmentId: 'DEP-006',
    departmentName: 'งานบริหาร บุคคล และการเงิน',
    role: 'ผู้สนับสนุนข้อมูล',
    personnelGroup: 'บุคลากรสายสนับสนุน',
    status: 'ACTIVE',
    createdAt: '2026-01-01T00:00:00Z',
  },
];
